import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type {  AppContext } from "next/app";
import { LoginProvider } from "../context/LoginContext";
import AppBar from "../components/Appbar";
import nookies from "nookies";
import { validate_jwt } from "@falgunpal/jwt-helper-ts";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quadiro",
  description: "Generated by create next app",
};

export default function RootLayout({children,login}: Readonly<{ children: React.ReactNode;}>&{login:boolean})  {
  return (
    <html lang="en"  style={{overflow:"hidden"}}> 
   
      <body  style={{margin:0}}  className={inter.className}>
      <LoginProvider initialLogin={login} >
      <AppBar>
        {children}
         </AppBar>
         </LoginProvider>
        </body>
    
    

    </html>
  );
}

RootLayout.getInitialProps = (appContext: AppContext) => {
  const ctx = appContext.ctx;
  const cookies = nookies.get(ctx);
  const token = cookies.token;
  const login = token ? validate_jwt(process.env.NEXT_PUBLIC_JWT_SECRET as string, token) : false;

  return { login };
};

